# SPDX-License-Identifier: MIT
"""ctios.design_lineage — inspiration is traced to a mechanism, or it
is not stated.

Seven facts about thinking motivated specific engineering invariants.
This module pins each one to a CONCRETE file + test that already exists
in the repo and FAILS if any cited mechanism is missing. The brain
facts are design lineage (motivation), never claims: the system is not
a brain, not cognition, not consciousness — see `forbidden`.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]


@dataclass(frozen=True)
class Mapping:
    fact: str           # the brain observation (motivation only)
    principle: str      # the engineering invariant it inspired
    mechanism: str      # concrete repo path that implements it
    test: str           # concrete repo path that guards it
    not_claimed: str    # the explicit non-claim


MAPPINGS: list[Mapping] = [
    Mapping(
        "Thinking is prediction, not reaction — the system is moved by "
        "its own prediction error (predictive-coding motivation).",
        "An agent infers a hidden regime from its OWN error, never from "
        "an exogenous change signal.",
        "src/ctios/predictive_simulation.py",
        "tests/test_predictive_simulation.py",
        "NOT Friston/biological predictive coding; a scalar/windowed "
        "estimator on synthetic streams.",
    ),
    Mapping(
        "Conscious decision lags the act (Libet) — the self is editor, "
        "not author.",
        "The verdict is decided by a falsifier PINNED before the run; "
        "reports edit a sealed result, they never author it "
        "(verdict-isolation).",
        "src/ctios/falsify.py",
        "tests/test_falsify_engine.py",
        "NOT a claim about consciousness or volition.",
    ),
    Mapping(
        "Attention is a gate, not a spotlight — it blocks the rest.",
        "The battery REJECTS inadmissible/degenerate probes and the "
        "lexicon BLOCKS unscoped surface; admission is by exclusion.",
        "src/ctios/falsifier_battery.py",
        "tests/test_deep_adversarial_probes.py",
        "NOT a model of attention.",
    ),
    Mapping(
        "Working memory is a 7±2 bottleneck; chunking removes the limit.",
        "A private theorem is chunked into a fixed small redacted "
        "skeleton; 6 lineages distilled to one primitive.",
        "src/ctios/change_detection.py",
        "tests/test_change_detection.py",
        "NOT a memory model.",
    ),
    Mapping(
        "Emotion is part of logic (Damasio) — pure logic with no value "
        "signal cannot decide.",
        "Automated logic cannot self-authorize the next experiment; a "
        "value-bearing human decision is structurally required.",
        "src/ctios/human_gate.py",
        "tests/test_human_gate.py",
        "NOT a model of emotion or affect.",
    ),
    Mapping(
        "Metacognition interferes with automatic performance — "
        "over-reflection is interference, not control.",
        "The science verdict is NOT asserted in CI; meta-monitoring "
        "(CI green) must not govern the object-level result.",
        "src/ctios/external_validation.py",
        "tests/test_external_validation_tamper.py",
        "NOT a claim about metacognition.",
    ),
    Mapping(
        "The brain does not separate 'I think' from 'I do' — a thought "
        "is a prototype of action (motor simulation).",
        "A hypothesis is not prose: it is a runnable Probe. Thinking "
        "the claim and doing the experiment are one artifact.",
        "src/ctios/spec_compiler.py",
        "tests/test_spec_compiler.py",
        "NOT mirror neurons or motor cortex.",
    ),
]

FORBIDDEN = (
    "NOT a brain, neurons, cognition, consciousness, sentience, "
    "intelligence, AGI, neuroplasticity, or a theory of time. The "
    "seven facts are design lineage (motivation) only; every claim is "
    "scoped to an executable mechanism + its test."
)


def missing_paths() -> list[str]:
    miss: list[str] = []
    for m in MAPPINGS:
        for p in (m.mechanism, m.test):
            if not (_ROOT / p).exists():
                miss.append(p)
    return miss


def write() -> Path:
    miss = missing_paths()
    out = _ROOT / "docs" / "DESIGN_LINEAGE_BRAIN_TO_MECHANISM.md"
    lines = [
        "# Design Lineage — Brain Motivation → Repo Mechanism",
        "",
        "Generated by `python -m ctios.design_lineage` (fails if any "
        "cited mechanism/test is missing — this is a guard, not prose).",
        "",
        "**Boundary.** " + FORBIDDEN,
        "",
        "| # | brain fact (motivation) | engineering invariant | mechanism | test | not claimed |",
        "|---|---|---|---|---|---|",
    ]
    for i, m in enumerate(MAPPINGS, 1):
        lines.append(
            f"| {i} | {m.fact} | {m.principle} | `{m.mechanism}` | "
            f"`{m.test}` | {m.not_claimed} |"
        )
    lines += [
        "",
        f"all_mechanisms_present: **{not miss}**",
        f"missing: {miss or '(none)'}",
        "",
        "If a row cannot point at a real, tested mechanism it is "
        "deleted, not softened. Inspiration without a mechanism is not "
        "stated here.",
    ]
    out.write_text("\n".join(lines) + "\n")
    (_ROOT / "evidence").mkdir(exist_ok=True)
    (_ROOT / "evidence" / "DESIGN_LINEAGE.json").write_text(
        json.dumps(
            {
                "mappings": [m.__dict__ for m in MAPPINGS],
                "missing": miss,
                "boundary": FORBIDDEN,
            },
            indent=2,
        )
    )
    return out


def main() -> int:
    miss = missing_paths()
    write()
    print(f"design lineage :: {len(MAPPINGS)} mappings, "
          f"missing={len(miss)}")
    return 0 if not miss else 1


if __name__ == "__main__":
    raise SystemExit(main())
